name: SteakGUI
main: tk.itstake.steakgui.SteakGUI
version: 1.2.7.1
description: GUI Maker for Minecraft
author: ITSTAKE
website: http://itstake.tk/steakgui
softdepend: [Vault]
commands:
  steakgui:
    description: Master Command
    aliases: [sg, steakg, sgui]
permissions:
  steakgui.open:













