name: SteakGUI
main: tk.itstake.steakgui.SteakGUI
version: 1.0.7
description: GUI Maker for Minecraft
author: ITSTAKE
website: http://itstake.tk/steakgui
depend: [Vault]
softdepend: [VariableTriggers, Skript]
commands:
  steakgui:
    description: Master Command
    aliases: [sg, steakg, sgui]
permissions:
  steakgui.open:
    default: true
  steakgui.open.other:
    default: op
  steakgui.setting:
    default: op

